from django.db import models


class FashionItem(models.Model):
    """Model for fashion items that will be analyzed by ML algorithms"""
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='fashion_items/')
    created_at = models.DateTimeField(auto_now_add=True)
    
    # ML-generated attributes
    style_category = models.CharField(max_length=100, blank=True)
    color_palette = models.JSONField(default=dict, blank=True)
    similarity_score = models.FloatField(null=True, blank=True)
    
    def __str__(self):
        return self.title


class StyleRecommendation(models.Model):
    """Model for style recommendations generated by ML algorithms"""
    source_item = models.ForeignKey(
        FashionItem, 
        on_delete=models.CASCADE,
        related_name='recommendations'
    )
    recommended_item = models.ForeignKey(
        FashionItem,
        on_delete=models.CASCADE,
        related_name='recommended_for'
    )
    similarity_score = models.FloatField()
    recommendation_reason = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('source_item', 'recommended_item')
        
    def __str__(self):
        return f"{self.source_item.title} → {self.recommended_item.title}"